spring.:
  application:
    name: gateway-app
server:
  port: 7070
zuul:
  prefix: /api
  routes:
    palindrome:
      path: /palin/**
      url: http://localhost:7071/palindrome
    anagram:
      path: /anag/**
      url: http://localhost:7072/anagram